cost function:
  cost type: '3D-Var'

  analysis variables: ['SNEQV'] # , 'SNOWH']  #seg faults if snowh not in state variables
  window begin: '2020-02-29T00:00:00Z'
  # window begin: '2017-01-01T00:00:00Z'
  window length: PT48H

  geometry:
    input_file: input/wrf_hydro_nwm_files/geometry_cfs_long_range_ens.nc

  background:
    read_from_file: 1
    date: &date 2020-03-01T00:00:00Z
    basename: "./INPUT/"
    filename_lsm: &RESTART input/wrf_hydro_nwm_files/RESTART.2020030100_DOMAIN1
    filename_hydro: &HYDRO_RST input/wrf_hydro_nwm_files/HYDRO_RST.2020-03-01_00:00_DOMAIN1
    state variables: ['SNEQV']  #, 'SNOWH']

  background error:
    covariance model: "wrf_hydro_nwm_jediCovar"
    date: *date
    sigma: 10
    rad: 100
    h_ver: 500
    analysis variables: ['SNEQV']

  variable change: 'Identity'
  observations:
  - obs error:
      covariance model: 'diagonal'
    obs operator:
      name: 'Identity'
    obs space:
      obsdatain:
        obsfile: 'input/obs/test_500_obs_owp_swe_csv_2020030100.nc'
      obsdataout:
        obsfile: 'output/3dvar/r100h500_500_obs_swe.nc'
      name: 'Simulate'
      simulated variables: ['swe'] # ['snow_depth']
  # - obs error:
  #     covariance model: 'diagonal'
  #   obs operator:
  #     name: 'Identity'
  #   obs space:
  #     obsdatain:
  #       obsfile: 'Data/make_obs/make_obs_3d.snow_depth_0000.nc'
  #     obsdataout:
  #       obsfile: 'Data/3dvar/3dvar.snow_depth.nc'
  #     name: 'Simulate'
  #     simulated variables: ['snow_depth']

final:
  diagnostics:
    departures: 'oman'

output:
  datadir: 'output/3dvar/'
  exp: '3dvar'
  first: PT0H
  frequency: PT1H
  type: 'an'
  
  filename_lsm: output/3dvar/analysis_r100h500_500_obs_swe.nc
  filename_hydro: *HYDRO_RST

variational:
  minimizer:
    algorithm: 'DRIPCG'
  iterations:
  - diagnostics:
      departures: 'ombg'
    gradient norm reduction: 1.0e-10
    ninner: 1
    geometry:
      input_file: input/wrf_hydro_nwm_files/geometry_cfs_long_range_ens.nc
    test: 'on'
