cost function:
  cost type: '3D-Var'

  analysis variables: &ana_vars ['SNEQV']
  window begin: '2016-12-31T23:30:00Z'
  window length: PT1H

  geometry:
    input_file: ./input/wrf_hydro_nwm_files/geometry_nwm_long_range_snow.nc

  background:
    read_from_file: 1
    date: &date 2017-01-01T00:00:00Z
    basename: "./INPUT/"
    filename_lsm: ./input/wrf_hydro_nwm_files/RESTART.2017010100_DOMAIN1
    filename_hydro: ./input/wrf_hydro_nwm_files/HYDRO_RST.2017-01-01_00:00_DOMAIN1
    state variables: *ana_vars

  background error:
    covariance model: SABER
    saber blocks:
    - saber block name: BUMP_NICAS
      saber central block: true
      iterative inverse: true
      input variables: *ana_vars
      output variables: *ana_vars
      bump:
        prefix: input/staticb/nicas_fixed
        verbosity: main
        strategy: specific_univariate
        load_nicas_local: true
    - saber block name: StdDev
      input variables: *ana_vars
      output variables: *ana_vars
      file:
        read_from_file: true
        date: *date
        basename: "./INPUT/"
        filename_lsm: ./input/staticb/stddev_fixed.lsm.an.2017-01-01T00:00:00Z
        filename_hydro: ./input/staticb/stddev_fixed.hyd.an.2017-01-01T00:00:00Z
        state variables: *ana_vars

  observations:
  - obs error:
      covariance model: 'diagonal'
    obs operator:
      name: 'Identity'
    obs space:
      obsdatain:
        obsfile: './input/obs/Single_obs_swe_2017010100.nc'
      obsdataout:
        obsfile: './output/3dvar/singleob_swe_obs.2017-01-01T00:00:00Z.PT0S'
      name: 'Simulate'
      simulated variables: ['swe']
  # - obs error:
  #     covariance model: 'diagonal'
  #   obs operator:
  #     name: 'Identity'
  #   obs space:
  #     obsdatain:
  #       obsfile: 'Data/make_obs/make_obs_3d.snow_depth_0000.nc'
  #     obsdataout:
  #       obsfile: 'Data/3dvar/3dvar.snow_depth.nc'
  #     name: 'Simulate'
  #     simulated variables: ['snow_depth']

final:
  diagnostics:
    departures: 'oman'

output:
  date: *date
  datadir: ./output/3dvar
  exp: 3dvar
  type: an

variational:
  minimizer:
    algorithm: 'DRIPCG'
  iterations:
  - diagnostics:
      departures: 'ombg'
    gradient norm reduction: 1.0e-10
    ninner: 10
    geometry:
      input_file: ./input/wrf_hydro_nwm_files/geometry_nwm_long_range_snow.nc
    test: 'on'
  - diagnostics:
      departures: 'ombg'
    gradient norm reduction: 1.0e-10
    ninner: 10
    geometry:
      input_file: ./input/wrf_hydro_nwm_files/geometry_nwm_long_range_snow.nc
    test: 'on'
