forecast length: PT1H
window begin: &date '2016-12-31T23:30:00Z'
# window begin: &date '2017-01-01T00:00:00Z'
window length: PT1H

geometry:
  input_file: input/wrf_hydro_nwm_files/geometry_nwm_long_range_snow.nc

model:
  name: 'WRF_HYDRO_NWM_JEDI'
  tstep: PT1H
  model variables: &model_vars ['SNEQV','SNOWH']

state:
  state variables: ['SNEQV','SNOWH']
  date: *date
  read_from_file: 1
  basename: ./INPUT/
  filename_lsm: input/wrf_hydro_nwm_files/RESTART.2017010100_DOMAIN1
  filename_hydro: input/wrf_hydro_nwm_files/HYDRO_RST.2017-01-01_00:00_DOMAIN1

observations:
- obs space:
    name: 'Simulate'
    simulated variables: ['swe']
    obsdatain:
      obsfile: 'input/obs/Single_obs_swe_out.nc'
    obsdataout:
      obsfile: 'output/hofx/hofx3d.swe_single_obs.nc'
  obs operator:
      name: 'Identity'
- obs space:
    name: 'Simulate'
    simulated variables: ['snow_depth']
    obsdatain:
      obsfile: 'input/obs/Single_obs_depth_out.nc'
    obsdataout:
      obsfile: 'output/hofx/hofx3d.depth_single_obs.nc'
  obs operator: 
      name: 'Identity'      

prints:
  frequency: PT1H
