forecast length: PT48H
window begin: &date '2020-02-29T00:00:00Z'
window length: PT48H

geometry:
  input_file: input/wrf_hydro_nwm_files/geometry_cfs_long_range_ens.nc

model:
  name: 'WRF_HYDRO_NWM_JEDI'
  tstep: PT48H
  model variables: &model_vars ['SNEQV', 'SNOWH']

state:
  state variables: ['SNEQV', 'SNOWH']
  date: *date
  read_from_file: 1
  basename: ./INPUT/
  filename_lsm: input/wrf_hydro_nwm_files/RESTART.2020030100_DOMAIN1
  filename_hydro: input/wrf_hydro_nwm_files/HYDRO_RST.2020-03-01_00:00_DOMAIN1

observations:
- obs space:
    name: 'Simulate'
    simulated variables: ['swe']
    obsdatain:
      obsfile: 'input/obs/conus_owp_snow_obs_swe_csv_2020030100.nc'
    obsdataout:
      obsfile: 'output/hofx/hofx3d_owp.swe.nc'
  obs operator:
      name: 'Identity'
- obs space:
    name: 'Simulate'
    simulated variables: ['snow_depth']
    obsdatain:
      obsfile: 'input/obs/conus_owp_snow_obs_depth_csv_2020030100.nc'
    obsdataout:
      obsfile: 'output/hofx/hofx3d_owp.snow_depth.nc'
  obs operator:
      name: 'Identity'

prints:
  frequency: PT1H
