forecast length: PT1H
window begin: &date '2019-03-01T00:30:00Z'
window length: PT1H

geometry:
  input_file: input/wrf_hydro_nwm_files/geometry_nwm_long_range_snow.nc

model:
  name: 'WRF_HYDRO_NWM_JEDI'
  tstep: PT1H
  model variables: &model_vars ['SNEQV','SNOWH']

state:
  state variables: ['SNEQV','SNOWH']
  date: *date
  read_from_file: 1
  basename: ./INPUT/
  filename_lsm: input/wrf_hydro_nwm_files/taylor_park/RESTART.2019030101_DOMAIN1
  filename_hydro: input/wrf_hydro_nwm_files/taylor_park/HYDRO_RST.2019-03-01_01:00_DOMAIN1

observations:
- obs space:
    name: 'Simulate'
    simulated variables: ['swe']
    obsdatain:
      obsfile: 'input/obs/taylor_park_obs_swe_2019-03-01T01:00:00Z.nc'
    obsdataout:
      obsfile: 'output/hofx/taylor_park_obs_swe_2019-03-01T01:00:00Z.nc'
  obs operator:
      name: 'Identity'
- obs space:
    name: 'Simulate'
    simulated variables: ['snow_depth']
    obsdatain:
      obsfile: 'input/obs/taylor_park_obs_depth_2019-03-01T01:00:00Z.nc'
    obsdataout:
      obsfile: 'output/hofx/taylor_park_obs_depth_2019-03-01T01:00:00Z.nc'
  obs operator: 
      name: 'Identity'      

prints:
  frequency: PT1H
