window begin: '2016-12-31T23:30:00Z'
window length: PT1H

geometry:
  input_file: ./input/wrf_hydro_nwm_files/geometry_nwm_long_range_snow.nc

background:
  members:
    - date: &date 2017-01-01T00:00:00Z
      read_from_file: 1
      filename_lsm: ./input/wrf_hydro_nwm_files/RESTART.2017010100_DOMAIN1_mem001
      filename_hydro: ./input/wrf_hydro_nwm_files/HYDRO_RST.2017-01-01_00:00_DOMAIN1
      state variables: ['SNOWH']
    - date: 2017-01-01T00:00:00Z
      read_from_file: 1
      filename_lsm: ./input/wrf_hydro_nwm_files/RESTART.2017010100_DOMAIN1_mem002
      filename_hydro: ./input/wrf_hydro_nwm_files/HYDRO_RST.2017-01-01_00:00_DOMAIN1
      state variables: ['SNOWH']  

observations:
- obs space:
    name: 'Simulate'
    distribution: InefficientDistribution
    simulated variables: ['snow_depth']
    obsdatain:
      obsfile: './input/obs/Single_obs_depth_out.nc'
    obsdataout:
      obsfile: './output/letkf/singleob.depth.nc'
  obs operator:
      name: 'Identity'    
  obs error:
      covariance model: 'diagonal'
  obs localizations:
  - localization method: Horizontal SOAR
#    lengthscale: 25000
#    soar horizontal decay: 0.001
    lengthscale: 250e3
    soar horizontal decay: 0.000021
    max nobs: 50
  - localization method: Vertical Brasnett
    vertical lengthscale: 700  

driver:
  save posterior mean: true
  save posterior ensemble: true
  save posterior mean increment: true

local ensemble DA:
  solver: LETKF
  inflation:
    rtps: 0.0
    rtpp: 0.0
    mult: 1.0

output:
  datadir: './output/letkf'
  date: *date
  exp: letkf
  type: 'ens'

output increment:
  datadir: './output/letkf'
  date: *date
  exp: letkf_inc
  type: 'ens'
