window begin: &date '2019-03-01T00:30:00Z'
window length: PT1H

geometry:
  input_file: ./input/wrf_hydro_nwm_files/geometry_nwm_long_range_snow.nc

background:
  members:
    - date: &date 2017-01-01T00:00:00Z
      read_from_file: 1
      filename_lsm: ./input/wrf_hydro_nwm_files/taylor_park/RESTART.2019030101_DOMAIN1_mem001
      filename_hydro: ./input/wrf_hydro_nwm_files/taylor_park/HYDRO_RST.2019-03-01_01:00_DOMAIN1
      state variables: ['SNOWH']
    - date: 2017-01-01T00:00:00Z
      read_from_file: 1
      filename_lsm: ./input/wrf_hydro_nwm_files/taylor_park/RESTART.2019030101_DOMAIN1_mem002
      filename_hydro: ./input/wrf_hydro_nwm_files/taylor_park/HYDRO_RST.2019-03-01_01:00_DOMAIN1
      state variables: ['SNOWH']         

observations:
- obs space:
    name: 'Simulate'
    distribution: InefficientDistribution
    simulated variables: ['snow_depth']
    obsdatain:
      obsfile: './input/obs/taylor_park_obs_depth_2019-03-01T01:00:00Z.nc'
    obsdataout:
      obsfile: './output/letkf/taylor_park/taylor_park_obs_depth_2019-03-01T01:00:00Z.nc'
  obs operator:
      name: 'Identity'    
  obs error:
      covariance model: 'diagonal'
  obs localizations:
  - localization method: Horizontal SOAR
#    lengthscale: 250e3
#    soar horizontal decay: 0.000021
    lengthscale: 250e3
    soar horizontal decay: 0.000021
    max nobs: 50
  - localization method: Vertical Brasnett
    vertical lengthscale: 700  

driver:
  save posterior mean: true
  save posterior ensemble: false
  save posterior mean increment: true

local ensemble DA:
  solver: LETKF
  inflation:
    rtps: 0.0
    rtpp: 0.0
    mult: 1.0

output:
  datadir: './output/letkf/taylor_park'
  date: *date
  exp: letkf
  type: 'ens'

output increment:
  datadir: './output/letkf/taylor_park'
  date: *date
  exp: letkf_inc
  type: 'ens'
